packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tanstack/react-query': ^5.59.15
  '@trpc/client': ^11.0.0-rc.477
  '@trpc/react-query': ^11.0.0-rc.477
  '@trpc/server': ^11.0.0-rc.477
  'superjson': ^2.2.2
  'zod': ^3.24.2
